name: Docker EDU - Build and Push to ACR

on:      
  workflow_dispatch:
    inputs:
      tags:
        description: "Docker TAG"
        required: true
        default: "master"

env:
  # Use the Azure Container Registry URL from secrets
  REGISTRY: ${{ secrets.AZURE_URL }}
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up BuildKit Docker container builder to build multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log into Azure Container Registry (ACR)
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      # Set a timestamp-based tag
      - name: Set environment variable for TAG
        run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Extract metadata for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.NOW }}

      # Build and push Docker image to ACR
      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ steps.meta.outputs.tags }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
